# Site Settings
title: Rossener
email: thiago@rossener.com
description: Blog pessoal de Thiago Rossener, desenvolvedor web apaixonado por desafios, tecnologia, pessoas e melhoramento pessoal.
baseurl: ""
url: "http://www.rossener.com"

# User Settings
username: Thiago Rossener
user_description: Desenvolvedor web, apaixonado por desafios, tecnologia, pessoas e melhoramento pessoal.
twitter_username: thiagorossener
github_username: thiagorossener
disqus_username: rossener

# Build settings
markdown: kramdown
permalink: /:title/

# Plugins
plugins:
  - jekyll-redirect-from
